### ISSUE TITLE
Passwords?

### ISSUE THREAD

**Issue by laheller** [gavodachs/docker-dachs#17]
Hi @chbrandt !

Are there any users/db passwords for the DACHS docker container we should know about?

BR,

Ladislav

**Comment by msdemlei** [comment]
On Wed, Oct 05, 2022 at 09:01:51AM -0700, Ladislav Heller wrote:
> Are there any users/db passwords for the DACHS docker container we
> should know about?

On the unix side, I don't think there are any.  To access the
database, become the dachsroot user, which can use the database
without passwords.

DaCHS internally uses three database roles, gavoadmin, gavo, and
untrusted, for which it arranges password authentication when you run
dachs init; you really shouldn't have any reason to mess with them.
But if you're curious, you will find the passwords in /var/gavo/etc.

**Comment by chbrandt** [comment]
Hi @laheller , did @msdemlei comment answer your question? If not, could you share the workflow (commands, terminal, etc) you are trying to do, please?

**Comment by laheller** [comment]
> Hi @laheller , did @msdemlei comment answer your question? If not, could you share the workflow (commands, terminal, etc) you are trying to do, please?

Yup, it did. Issue can be closed.

**Comment by chbrandt** [comment]
Great! Thanks
